export_data:
  fields:
    account:
      required: false
      example: John Smith
      selector:
        text:
    file_path:
      required: false
      example: /config/tonal_backup.json.gz
      selector:
        text:
    full:
      required: false
      default: false
      selector:
        boolean:
    gzip:
      required: false
      default: true
      selector:
        boolean:
